# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IpInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddr', models.CharField(max_length=20)),
                ('mac', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=30)),
                ('hostname', models.CharField(max_length=50)),
                ('describe', models.CharField(max_length=300)),
                ('create_at', models.DateTimeField()),
                ('flag', models.IntegerField()),
            ],
        ),
    ]
